### ISSUE TITLE
Broken link to Solo Project Guide on Programs & Services page

### ISSUE THREAD

**Issue by terrifricker** [chingu-voyages/Handbook#53]
![Screen Shot 2023-10-22 at 1 05 34 PM](https://github.com/chingu-voyages/Handbook/assets/51532684/f33e097f-eefe-487b-9408-c23ffc556cf2)

![Screen Shot 2023-10-22 at 1 06 04 PM](https://github.com/chingu-voyages/Handbook/assets/51532684/bf28b0c2-710d-448b-a2ff-303f0e39baea)

**Comment by jdmedlock** [comment]
This has been resolved by #55 Thanks for your PR @terrifricker
